### ISSUE TITLE
Duplicate source files issue in Intellij

### ISSUE THREAD

**Issue by mkotsbak** [ebiznext/sbt-cxf-wsdl2java#11]
Working with a project that uses this plugin in Intellij causes duplicate source files issue. It seems to be caused by both
[project]/target/scala-2.11/src_managed/main and
[project]/target/scala-2.11/src_managed/main/cxf
being in the managed source directories.

Is there a need to have it inside the cxf directory? Apparently the problem is solved by outcommenting this line:
sourceManaged in CxfConfig := sourceManaged.value / "cxf",

**Comment by theBlackDragon** [comment]
This location is what is being suggested by the Sbt documentation, unfortunately Java source generating plugins do this differently, resulting in lots of confusion among people and tools used to work with the default Maven structure, on top of that there seems to be some confusion in the Sbt camp and there are some Sbt plugins do not adhere to what the documentation prescribes, resulting in this problem.

I'd be inclined to say the problem is with Sbt adding the "main" subdirectory to "src_managed" and I'd be in favour of getting rid of that. I feel that removing the "cxf" subdirectory in the plugin will only lead to problems down the road. Either way, some standard needs to be decided on at Sbt's side and plugins need to be updated accordingly (see sbt/sbt#1664). As long as the Sbt people don't make up their minds I'd argue that sticking to what's documented is the safest thing to do. (and as a result I'd argue that IDEA adding "main" as a source directory for an Sbt project is *wrong* based on what is currently in the Sbt documentation).

Please weigh in on the Sbt issue, the sooner this issue can be put to rest the better as far as I'm concerned as getting multiple source generating plugins, some of which do follow the documentation (like this one) and others who don't follow the documentation, to work together has been rather a painful affair.

**Comment by mkotsbak** [comment]
What about doing a workaround until a better solution is found by following this advice:
"A source generation task should generate sources in sourceManaged, or if it wants to keep the source files it generates separate from other source generation tasks, it should generate sources to a sub directory in crossTarget and add that directory to managedSourceDirectories."

That is, add the directory in crossTarget instead of sourceManaged directory.

As it is now, enabling autoimport in IntelliJ makes it not usable.

**Comment by theBlackDragon** [comment]
I can confirm that this works around the problem and appears to be working in IDEA at least. It's also unlikely to conflict with whatever is decided on the Sbt side later, which is a nice bonus imho.

I'll see if I can find the time to test this solution with Eclipse.

**Comment by mkotsbak** [comment]
Great. I see no reason it should not work in Eclipse. Also not sure if it breaks in Eclipse as with IntelliJ.

**Comment by theBlackDragon** [comment]
Neither did I, but it felt safer to check and I can confirm it works in Eclipse as well.
